name: Release Executable

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add Apple target
        run: rustup target add aarch64-apple-darwin

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-apple-darwin

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-msvc

      - name: Prepare binaries
        run: |
          cp target/aarch64-apple-darwin/release/salsa ./salsa-aarch64-apple-darwin
          cp target/x86_64-unknown-linux-gnu/release/salsa ./salsa-x86_64
          cp target/aarch64-unknown-linux-gnu/release/salsa ./salsa-aarch64
          cp target/x86_64-pc-windows-msvc/release/salsa.exe ./salsa-x86_64.exe

      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: salsa-*
