name: Release Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the executable
        run: |
          sudo apt update && sudo apt install libc6
          cargo install cross
          cross build --release --target x86_64-unknown-linux-gnu
          cross build --release --target armv7-unknown-linux-gnueabihf
          cross build --release --target aarch64-unknown-linux-gnu
          cross build --release --target i686-unknown-linux-gnu
          cross build --release --target riscv64gc-unknown-linux-gnu
      
      - name: Prepare binaries
        run: |
          cp target/riscv64gc-unknown-linux-gnu/release/salsa ./salsa-riscv64gc
          cp target/x86_64-unknown-linux-gnu/release/salsa ./salsa-x86_64
          cp target/armv7-unknown-linux-gnueabihf/release/salsa ./salsa-armv7
          cp target/aarch64-unknown-linux-gnu/release/salsa ./salsa-aarch64
          cp target/i686-unknown-linux-gnu/release/salsa ./salsa-i686

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
